### ISSUE TITLE
Get wrong metamon numbers

### ISSUE THREAD

**Issue by b5prolh** [MetaMon-game-player/MetamonPlayer#1]
After try, I see it get not enough metamon numbers in my game asset. Pls check it. Thanks you

**Comment by quyennguyenvan** [comment]
@b5prolh  you can modify at the line 203 from 60 to 1000, it can retrieve all your mtm

**Comment by Afaelin** [comment]
Should have been resolved with last patch @b5prolh 
Can you confirm that’s what you were talking about?
