### ISSUE TITLE
Number of minted egg is not accurate 

### ISSUE THREAD

**Issue by Hennessyng** [MetaMon-game-player/MetamonPlayer#10]
Bot minted 2 eggs from 2000 egg fragments at the same time but the counter counted as 1 egg only

**Comment by dr-artio** [comment]
This is because now they mint in one request so in order to see how many eggs were minted go to transaction history and ignore message in command line.

**Comment by ntqhungdx** [comment]
I've fixed this issue in my version. Below is the new mint_eggs function to fix this issue.

    def mint_eggs(self):
        self.init_token()

        headers = {
            "accessToken": self.token,
        }
        payload = {"address": self.address}

        # Check current egg fragments
        check_bag_res = post_formdata(payload, CHECK_BAG_URL, headers)
        items = check_bag_res.get("data", {}).get("item")
        total_egg_fragments = 0;

        for item in items:
            if item.get("bpType") == 1:
                total_egg_fragments = item.get("bpNum")
                break

        total_egg = int(int(total_egg_fragments) / 1000);

        if total_egg < 1:
            print("You don't have enough egg to mint")
            return

        # Mint egg
        res = post_formdata(payload, MINT_EGG_URL, headers)
        code = res.get("code")
        if code != "SUCCESS":
            print("Mint egg failed!")
            return

        print(f"Minted Eggs Total: {total_egg}")

**Comment by Hennessyng** [comment]
Thanks! Where can I find the  "CHECK_BAG_URL"?

**Comment by MetaMon-game-player** [comment]
Added to the code, thanks
