### ISSUE TITLE
fight crashed because max exp reached 600 XP

### ISSUE THREAD

**Issue by ecalzz** [MetaMon-game-player/MetamonPlayer#11]
There are new limitation in the game, when metamon exp reached 600 xp. it wont be able to fight anymore. and if it is reached during the fight. the script will crashed.

please add check_exp before each fight so when metamon exp reached 600 xp and there are no potions or no upgrade parameters are set the script will stop and will not attempt to do a fight

**Comment by MetaMon-game-player** [comment]
We are aware of issue, but it does not affect most of plays and bot is for devs. Everyone can customize for their needs. If you cant program on Python, better to avoid using anything like this anyway

**Comment by thucngv** [comment]
@ecalzz you can refer to this solution of mine
https://github.com/thucngv/MetamonPlayer/commit/41850c1bec88448cb0dbf4c993661eff81bb5479
