### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by khoavodoj** [MetaMon-game-player/MetamonPlayer#13]
Just today the program don't run. Before it's work great. 
Is there any update ?

**Comment by ntthinh2006** [comment]
Yes, tool not working today. Please fix.

**Comment by Afaelin** [comment]
It's since they changed the Metamon interface, it seems there's no more page. Code is going to be fixed asap :-)

**Comment by nguyenngochanh** [comment]
At  """ Obtain list of metamons on the wallet""" replace function as bellow:
    def get_wallet_properties(self):
        """ Obtain list of metamons on the wallet"""
        data = []
        page = 1
        while True:
            payload = {"address": self.address, "page": page, "pageSize": 60}
            headers = {
                "accessToken": self.token,
            }
            response = post_formdata(payload, WALLET_PROPERTY_LIST, headers)
            mtms = response.get("data", {}).get("metamonList", [])
            if len(mtms) > 0:
                data.extend(mtms)
                page += 1
                return data
            else:
                break
        return data

**Comment by Afaelin** [comment]
I fixed it, now waiting for @MetaMon-game-player to accept the pull request.

**Comment by MetaMon-game-player** [comment]
I fixed it myself, thanks for raising issue
