### ISSUE TITLE
Message wrong number minted Eggs total

### ISSUE THREAD

**Issue by xlxl85** [MetaMon-game-player/MetamonPlayer#4]
Message wrong number minted Eggs total
Minted Eggs Total: 1
But actually Minted Eggs Total is 6

**Comment by Burstall** [comment]
they changed the method being used (same in game) it now simply mints all that it can. as a result the status code returned is only ever going to be 1 (or zero if not enough shards for any egg I presume)

**Comment by MetaMon-game-player** [comment]
Yes it mints once instead of each egg so will have to read egg balance before and after to see how many egg was was minted. In meantime login to game and check transaction history to see actual number
