### ISSUE TITLE
Get runtime error

### ISSUE THREAD

**Issue by JohnWick2008** [MetaMon-game-player/MetamonPlayer#5]
Dear Authors,
In 3 days lated, we got runtime error for each 5-10 metamons, maybe from bsc network. So we have to re run around 3-4 times to finish our wallet.
Would you have any solution to handle it!
Thanks so much!

**Comment by MetaMon-game-player** [comment]
Sometimes due to connection or server issues it crashes, new update will have option to retry request if failed few times before giving up.

**Comment by MetaMon-game-player** [comment]
Added few tries before giving up
