### ISSUE TITLE
Create .tsv file

### ISSUE THREAD

**Issue by thucngv** [MetaMon-game-player/MetamonPlayer#6]
Some people don't know how to create .tsv files.
I wrote this code to help generate .tsv file automatically after login
After login success, in Chrome open Developer Tools, switch to tab Console, paste the bellow script => Enter

`(()=>{var e=[["name","address","sign","msg"],["Wallet1",sessionStorage.getItem("account-address"),sessionStorage.getItem("connect-sign"),sessionStorage.getItem("connect-signMsg")]],t="";e.forEach(function(n,a){dataString=n.join("\t"),t+=a<e.length?dataString+"\n":dataString});!function(e,t,n){var a=document.createElement("a");n=n||"application/octet-stream",navigator.msSaveBlob?navigator.msSaveBlob(new Blob([e],{type:n}),t):URL&&"download"in a?(a.href=URL.createObjectURL(new Blob([e],{type:n})),a.setAttribute("download",t),document.body.appendChild(a),a.click(),document.body.removeChild(a)):location.href="data:application/octet-stream,"+encodeURIComponent(e)}(t,"wallets.tsv","text/tsv;encoding:utf-8")})();`

**Comment by locbud** [comment]
how can we run the code above @thucngv ?

**Comment by thucngv** [comment]
> how can we run the code above @thucngv ?

After login success, in Chrome open Developer Tools, switch to tab Console, paste the [Script](https://github.com/MetaMon-game-player/MetamonPlayer/issues/6#issue-1081844995) => Enter

**Comment by menduong** [comment]
Cannot get sign after game update today. Anyone like me?

**Comment by MetaMon-game-player** [comment]
Added to README.md
