### ISSUE TITLE
Cannot run code

### ISSUE THREAD

**Issue by calvinle87** [MetaMon-game-player/MetamonPlayer#9]
Hi,
After I ran the code, this is what I get:

python metamon_play.py -i /Users/calvinle/MetaFrag
Traceback (most recent call last):
  File "/Users/calvinle/metamon_play.py", line 350, in <module>
    with open(args.input_tsv) as csvfile:
IsADirectoryError: [Errno 21] Is a directory: '/Users/calvinle/MetaFrag'

I followed the instruction on how to save the tsv from the "issue". 
The "metamon_play.py" is stored in "/Users/calvinle/"
The "wallets.tsv" is stored in "/Users/calvinle/MetaFrag/"

Thanks

**Comment by Afaelin** [comment]
Hi,

Maybe try without parameters with the wallets.tsv file in the root folder, next to the metamon_play.py.
Will try to fix this asap if I can reproduce :-)

**Comment by MetaMon-game-player** [comment]
If -i is specified then path to wallets.tsv should be provided, full path not just directory.
